# Generated by Django 3.0.2 on 2020-01-29 19:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=None, max_length=30, unique=True, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='shopping.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='need_date',
            field=models.DateTimeField(verbose_name='Needed before'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'szt.'), ('box', 'op.'), ('bottle', 'but.'), ('kg', 'kg'), ('dag', 'dag'), ('l', 'l'), ('cm', 'cm'), ('m', 'm')], default='pcs', max_length=6),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Entry date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Product')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['add_date'],
            },
        ),
    ]
