# Generated by Django 3.0.2 on 2020-02-03 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0005_auto_20200201_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Lista'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.FloatField(blank=True, default=0, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, through='shopping.Entry', to='shopping.Category', verbose_name='Lista'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.CharField(blank=True, default='-', max_length=100, verbose_name='Uwagi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Prywatne'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'szt.'), ('box', 'op.'), ('bottle', 'but.'), ('kg', 'kg'), ('dag', 'dag'), ('l', 'l'), ('cm', 'cm'), ('m', 'm')], default='pcs', max_length=6, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='product',
            name='urgency',
            field=models.CharField(choices=[('yes', 'Tak'), ('no', 'Nie')], default='no', max_length=10, verbose_name='Pilne'),
        ),
    ]
