# Generated by Django 3.0.2 on 2020-02-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20200203_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nazwa listy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, through='shopping.Entry', to='shopping.Category', verbose_name='Nazwa listy'),
        ),
    ]
