# Generated by Django 3.0.2 on 2020-02-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20200203_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='urgency',
        ),
    ]
